// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyhraaeswxuscmpjtlfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5aHJhYWVzd3h1c2NtcGp0bGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NjgwMTAsImV4cCI6MjA1NDQ0NDAxMH0._hSYwHyUQ6hYF8ZCFcnniWaFgpnYLlojdNw7O4CDsWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);